### PR TITLE
Powerups

### PR DESCRIPTION
**Pull request by JasperVanEsveld**
Power ups will make the level easier for the player to complete.
 There is a 50/50 chance a power up will drop and it depends on the ball size what power up will drop.
Currently there are 3 powerups: SlowBall-, FastArrow-, Movement- PowerUp.
Everything is tested and build is succesfull.

### CODE REVIEW

**Comment by mlrprananta** [comment]
IsActive() in PowerUp is missing javadoc

**Comment by JasperVanEsveld** [comment]
Thnx, missed that one.

**Comment by JasperVanEsveld** [comment]
I will close this request and add the java doc.
Will resolve the conflicts before merging as well.

**Comment by JasperVanEsveld** [comment]
Added the missing comment and solved the conflicts.
Also dissabled vsync since it was causing some issues in windowed mode.

**Comment by mtavasszy** [comment]
to me IsActive() in PowerUp is still missing javadoc. Other than that, good job.

**Comment by JasperVanEsveld** [comment]
Hm that's odd i'm sure it is added, maybe you need to refresh eclipse?

**Comment by arjanvanschendel** [comment]
The javadoc for IsActive() is there, merging:)

**Pull request merged**
