### PR TITLE
Added simple frameCounter to check performance <feature

### PR DESCRIPTION
**Pull request by arjanvanschendel**
Added a simple FPScounter in the bottom-left corner of the screen.

pls merge

### CODE REVIEW

**Comment by JasperVanEsveld** [comment]
Nice good for debugging.
Maybe we can add it in the options menu?

**Comment by arjanvanschendel** [comment]
We could when we release the beta, until then I think it is useful for everyone.

**Comment by mtavasszy** [comment]
damn sweet improv boi

**Comment by arjanvanschendel** [comment]
The branch is up-to-date with the master now, but we found some bugs. Matthias will work on this, closing this for now.

**Pull request closed without merging**
