### PR TITLE
Check style

### PR DESCRIPTION
**Pull request by JasperVanEsveld**
Big overhaul which fixes all warnings found by Checkstyle in both the tests as well as the main code.
<documentation

### CODE REVIEW

**Comment by JasperVanEsveld** [comment]
Please check this pullrequest first: https://github.com/arjanvanschendel/KauwgombalMisere/pull/36

**Comment by JasperVanEsveld** [comment]
Now that ExtraLife is merged this can be reopened

**Comment by arjanvanschendel** [comment]
You chickity-checkstyled yourself before you rekstyled yourself, very well done.

pls fix travis first though!

**Comment by bartziengs** [comment]
one unsuccessful check, please take a look

**Comment by JasperVanEsveld** [comment]
Oké checking it now.

**Comment by JasperVanEsveld** [comment]
It should be fixed now.

**Pull request merged**
