### PR TITLE
Lives plus

### PR DESCRIPTION
**Pull request by mtavasszy**
this branch contains a simple UI addition and spelling improvements

### CODE REVIEW

**Comment by mlrprananta** [comment]
Has my approval

**Comment by arjanvanschendel** [comment]
Looks good!

Please resolve the conflicts before we can merge.

**Comment by JasperVanEsveld** [comment]
Yeah looks good, but I did find a bug.
If you die and press space while in the main menu you go back to the last level with 2 lives.
 Maybe worth looking into before merging?

**Comment by arjanvanschendel** [comment]
I've already fixed that in another branch, so that should be merged soon. I'll merge this in a second.

**Comment by JasperVanEsveld** [comment]
Oké good job!
I think this is ready to be merged

**Pull request merged**
