### PR TITLE
Score popups

### PR DESCRIPTION
**Pull request by bartziengs**
please check the new feature

### CODE REVIEW

**Comment by arjanvanschendel** [comment]
Feature checked. Looks absolutely stunning. 9/10

If you resolve the conflicts: 10/10.

**Comment by mlrprananta** [comment]
Please resolve conflicts

**Comment by JasperVanEsveld** [comment]
RESOLVE THEM CONFLICTS

**Comment by mtavasszy** [comment]
looks nice, but conflicts need to be fixed before merge

**Comment by arjanvanschendel** [comment]
Conflicts resolved, merging

**Pull request merged**
